# Loan Prediction

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part-1 Data Preprocessing

### Importing the dataset

In [2]:
dataset=pd.read_csv('Training Set.csv')
X=dataset.iloc[:, 1:-1].values
Y=dataset.iloc[:, -1].values

In [3]:
print(X)

[['Male' 'No' 0.0 ... 360.0 1.0 'Urban']
 ['Male' 'Yes' 1.0 ... 360.0 1.0 'Rural']
 ['Male' 'Yes' 0.0 ... 360.0 1.0 'Urban']
 ...
 ['Male' 'Yes' 1.0 ... 360.0 1.0 'Urban']
 ['Male' 'Yes' 2.0 ... 360.0 1.0 'Urban']
 ['Female' 'No' 0.0 ... 360.0 0.0 'Semiurban']]


### Taking care of missing data

In [4]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X=imputer.fit_transform(X)

In [5]:
print(X)

[['Male' 'No' 0.0 ... 360.0 1.0 'Urban']
 ['Male' 'Yes' 1.0 ... 360.0 1.0 'Rural']
 ['Male' 'Yes' 0.0 ... 360.0 1.0 'Urban']
 ...
 ['Male' 'Yes' 1.0 ... 360.0 1.0 'Urban']
 ['Male' 'Yes' 2.0 ... 360.0 1.0 'Urban']
 ['Female' 'No' 0.0 ... 360.0 0.0 'Semiurban']]


### Encoding Categorical Datas

#### Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le_1=LabelEncoder()
X[:, 0]=le_1.fit_transform(X[:, 0])

In [8]:
le_2=LabelEncoder()
X[:, 1]=le_2.fit_transform(X[:, 1])

In [9]:
le_3=LabelEncoder()
X[:, 3]=le_3.fit_transform(X[:, 3])

In [10]:
le_4=LabelEncoder()
X[:, 4]=le_4.fit_transform(X[:, 4])

In [11]:
le_Y=LabelEncoder()
Y=le_Y.fit_transform(Y)

#### One Hot Encoding

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [10])], remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 ... 120.0 360.0 1.0]
 [1.0 0.0 0.0 ... 128.0 360.0 1.0]
 [0.0 0.0 1.0 ... 66.0 360.0 1.0]
 ...
 [0.0 0.0 1.0 ... 253.0 360.0 1.0]
 [0.0 0.0 1.0 ... 187.0 360.0 1.0]
 [0.0 1.0 0.0 ... 133.0 360.0 0.0]]


### Splitting the Dataset

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.2, random_state=0)

### Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

## Part-2 Building the ANN

### Initializing the ANN

In [15]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part-3 Training the ANN

### Compiling the ANN

In [19]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training Set

In [20]:
ann.fit(X_train, Y_train, batch_size=32, epochs=100)

Epoch 1/100
16/16 [==============================] - 1s 1ms/step - loss: 1.0843 - accuracy: 0.3539
Epoch 2/100
16/16 [==============================] - 0s 1ms/step - loss: 0.9968 - accuracy: 0.3353
Epoch 3/100
16/16 [==============================] - 0s 1ms/step - loss: 0.9519 - accuracy: 0.2881
Epoch 4/100
16/16 [==============================] - 0s 1ms/step - loss: 0.8826 - accuracy: 0.3136
Epoch 5/100
16/16 [==============================] - 0s 1ms/step - loss: 0.8156 - accuracy: 0.3539
Epoch 6/100
16/16 [==============================] - 0s 1ms/step - loss: 0.7843 - accuracy: 0.3803
Epoch 7/100
16/16 [==============================] - 0s 1ms/step - loss: 0.7558 - accuracy: 0.4194
Epoch 8/100
16/16 [==============================] - 0s 2ms/step - loss: 0.7206 - accuracy: 0.4465
Epoch 9/100
16/16 [==============================] - 0s 1ms/step - loss: 0.7108 - accuracy: 0.4354
Epoch 10/100
16/16 [==============================] - 0s 1ms/step - loss: 0.7029 - accuracy: 0.4574
Epoch 11/

## Part-4 Making the predictions and evaluating the model

### Predicting the Test Set Results

In [21]:
Y_pred=ann.predict(X_test)>0.5
Y_pred=Y_pred.reshape(-1)
le_Y1=LabelEncoder()
Y_pred=le_Y1.fit_transform(Y_pred)
for i in range(0, len(Y_test)):
  print(Y_test[i], "  ", Y_pred[i])

1    1
0    1
1    1
0    1
1    1
0    0
1    1
1    1
0    0
1    1
1    1
1    1
1    1
1    1
1    1
0    1
0    1
1    1
1    1
0    0
0    0
1    1
1    1
1    1
1    1
1    1
1    1
1    1
0    0
0    0
1    1
1    1
1    1
1    1
1    1
0    0
1    1
1    1
1    1
1    1
1    1
0    0
1    1
1    1
1    1
1    1
1    1
1    1
0    1
1    1
1    1
1    1
1    1
1    1
1    1
1    1
1    1
0    1
1    1
1    1
1    0
0    1
1    1
0    0
1    1
1    1
1    1
1    1
1    1
1    1
0    1
1    1
1    1
1    1
1    1
1    1
0    0
0    1
1    1
0    0
1    0
0    1
0    1
1    1
0    0
1    1
1    1
1    1
1    1
1    1
1    1
0    1
0    1
0    0
1    1
0    0
1    1
1    1
1    1
1    1
1    1
1    1
1    1
0    1
1    1
1    1
1    1
1    1
1    1
0    1
1    1
0    1
0    0
1    1
0    0
1    0
1    1
1    1
1    1
1    1
1    1
0    0
1    1


### Making the Confusion Matrix

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(Y_test, Y_pred)
ac=accuracy_score(Y_test, Y_pred)
print(ac*100)

84.5528455284553
